# 8-bit ripple-carry adder generated by ABC on Mon Sep 24 18:16:14 2012
.model ADD8
.inputs a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7
.outputs s0 s1 s2 s3 s4 s5 s6 s7 s8
.names c
.subckt FA a=a0 b=b0 cin=c s=s0 cout=0
.subckt FA a=a1 b=b1 cin=0 s=s1 cout=1
.subckt FA a=a2 b=b2 cin=1 s=s2 cout=2
.subckt FA a=a3 b=b3 cin=2 s=s3 cout=3
.subckt FA a=a4 b=b4 cin=3 s=s4 cout=4
.subckt FA a=a5 b=b5 cin=4 s=s5 cout=5
.subckt FA a=a6 b=b6 cin=5 s=s6 cout=6
.subckt FA a=a7 b=b7 cin=6 s=s7 cout=s8
.end

.model FA
.inputs a b cin
.outputs s cout
.names a b k
10 1
01 1
.names k cin s
10 1
01 1
.names a b cin cout
11- 1
1-1 1
-11 1
.end

